train:
  batch_size: 256
  sample_size: 1000
  learning_rate: 0.001
  epochs: 10
  sample_epoch: 1
  buffer_size: 20000
  seed: 123
  validation_epoch: 10
  video_path: ./video
env:
  env_name: 'relocate-v0'
model:
  hidden_dim:
    - 256
    - 64
    - 32
device: cuda
test:
  max_timesteps: 200